// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaa7tiQDwhuCkuDDWCkUKIR0n5bS5WvEs',
    appId: '1:308608323964:web:cd4b3c8601ccef5692d4f9',
    messagingSenderId: '308608323964',
    projectId: 'expenseapp-cb589',
    authDomain: 'expenseapp-cb589.firebaseapp.com',
    storageBucket: 'expenseapp-cb589.firebasestorage.app',
    measurementId: 'G-4VLK4W0MFG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFThPYOjc9RqmZU6Sf4S8XlN3ha-730Us',
    appId: '1:308608323964:ios:9927cd560d3af23b92d4f9',
    messagingSenderId: '308608323964',
    projectId: 'expenseapp-cb589',
    storageBucket: 'expenseapp-cb589.firebasestorage.app',
    iosBundleId: 'com.example.p005ExpenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFThPYOjc9RqmZU6Sf4S8XlN3ha-730Us',
    appId: '1:308608323964:ios:9927cd560d3af23b92d4f9',
    messagingSenderId: '308608323964',
    projectId: 'expenseapp-cb589',
    storageBucket: 'expenseapp-cb589.firebasestorage.app',
    iosBundleId: 'com.example.p005ExpenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaa7tiQDwhuCkuDDWCkUKIR0n5bS5WvEs',
    appId: '1:308608323964:web:58f29d66e06dc65792d4f9',
    messagingSenderId: '308608323964',
    projectId: 'expenseapp-cb589',
    authDomain: 'expenseapp-cb589.firebaseapp.com',
    storageBucket: 'expenseapp-cb589.firebasestorage.app',
    measurementId: 'G-BTZS6Z4E39',
  );

}